// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`

interface Env {
    IP_WHITELIST?: string;
}

declare module '*.html' {
    const html: string;
    export default html;
}
