// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
interface Env {
    SUB_LIST_URL?: string;
    SUB_API?: string;
    SUB_CONFIG?: string;

    KV_NAMESPACE_ID?: string;
    ACCOUNT_ID?: string;
    KV_API_TOKEN?: string;
    ACCOUNT_EMAIL?: string;
}
