// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
    IP_WHITELIST?: string;
    MAX_CONTENT_LENGTH: number;
    ALLOWED_METHODS: string[];
}
