// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`

interface Env {
    // ip白名单
    IP_WHITELIST?: string;
    // 最大文件大小  50M
    MAX_SIZE?: string;
}
