// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`

interface Env {
    // ip白名单
    IP_WHITELIST?: string;
    // 最大重试次数  5
    MAX_RETRIES?: number;
}
