// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`

interface Env {
    GITHUB_TOKEN: string;
    GITHUB_USERNAME?: string;
    REPO_NAME?: string;
    REPO_BRANCH?: string;
    LINKS: string;
    RETRY?: string;

    TG_TOKEN?: string;
    TG_ID?: string;

    KV_API_TOKEN: string;
    KV_NAMESPACE_ID: string;
    ACCOUNT_ID: string;
    ACCOUNT_EMAIL: string;

    SUB: string;
    SUB_CONFIG: string;
    SUB_URLS: string;
}
