// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`

interface Env {
    GITHUB_TOKEN: string;
    GITHUB_USERNAME?: string;
    REPO_NAME?: string;
    REPO_BRANCH?: string;
    LINKS: string;

    SUBS: string;
    UPLOAD_URL: string;
    REMOTE_CONFIG?: string;

    SUB_CONVERT?: string;
}
