// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`

interface Env {
    GITHUB_TOKEN: string;
    GITHUB_USERNAME?: string;
    REPO_NAME?: string;
    REPO_BRANCH?: string;
    LINKS: string;
    RETRY?: string;

    TELEGRAM_BOT_TOKEN?: string;
    TELEGRAM_CHAT_ID?: string;
}
