# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: build and publish

on:
    release:
        types: [created]
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
              with:
                  version: latest
            - uses: actions/setup-node@v4
              with:
                  node-version: latest
            - run: pnpm install
            - run: pnpm run build:pages:docker
    deploy:
    runs-on: ubuntu-latest
    needs: build # Ensure the build job completes before deploying
    steps:
        - uses: actions/checkout@v4
        - name: Download artifact
          uses: actions/download-artifact@v3
          with:
              name: build
              path: packages/docker-proxy/pages
        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v3
          with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_dir: packages/docker-proxy/pages
              publish_branch: release-docker
