name: Release Workflow

on:
    push:
        branches:
            - main
        paths-ignore:
            - README.md
            - packages/**/*.md
            - LICENSE

jobs:
    determine_release_type:
        runs-on: ubuntu-latest
        outputs:
            release_type: ${{ steps.set_release_type.outputs.type }}
            release_time: ${{ steps.set_time.outputs.time }} # 添加输出时间
        steps:
            - name: Determine release type
              id: set_release_type
              run: |
                  commit_message="${{ github.event.head_commit.message }}"
                  if [[ "$commit_message" =~ ^docker: ]]; then
                      echo "type=docker" >> $GITHUB_OUTPUT
                  elif [[ "$commit_message" =~ ^npm: ]]; then
                      echo "type=npm" >> $GITHUB_OUTPUT
                  elif [[ "$commit_message" =~ ^cargo: ]]; then
                      echo "type=cargo" >> $GITHUB_OUTPUT
                  elif [[ "$commit_message" =~ ^feat: ]]; then
                      echo "type=feat" >> $GITHUB_OUTPUT
                  else
                      echo "type=unknown" >> $GITHUB_OUTPUT
                  fi

            - name: Set current time
              id: set_time
              run: |
                  current_time=$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S')
                  echo "time=${current_time}" >> $GITHUB_OUTPUT  # 设置输出变量
                  echo "Current time: $current_time"  # 打印当前时间

            - name: Print release type
              run: |
                  echo "Release type: ${{ steps.set_release_type.outputs.type }}"
                  echo "Current time: ${{ steps.set_time.outputs.time }}"

    run_docker_release:
        needs: determine_release_type
        if: needs.determine_release_type.outputs.release_type == 'docker'
        runs-on: ubuntu-latest
        steps:
            - name: Run Docker Release
              uses: ./.github/workflows/release-docker.yml
              with:
                  DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
                  TIME: ${{ needs.determine_release_type.outputs.release_time }} # 传递时间

    run_npm_release:
        needs: determine_release_type
        if: needs.determine_release_type.outputs.release_type == 'npm'
        runs-on: ubuntu-latest
        steps:
            - name: Run NPM Release
              uses: ./.github/workflows/release-npm.yml
              with:
                  DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
                  TIME: ${{ needs.determine_release_type.outputs.release_time }} # 传递时间

    run_cargo_release:
        needs: determine_release_type
        if: needs.determine_release_type.outputs.release_type == 'cargo'
        runs-on: ubuntu-latest
        steps:
            - name: Run Cargo Release
              uses: ./.github/workflows/release-cargo.yml
              with:
                  DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
                  TIME: ${{ needs.determine_release_type.outputs.release_time }} # 传递时间

    unknown_release_type:
        needs: determine_release_type
        if: needs.determine_release_type.outputs.release_type == 'unknown'
        runs-on: ubuntu-latest
        steps:
            - run: |
                  echo "Unknown release type. No action taken."
                  exit 1
