name: docker release

on:
    workflow_call:
        secrets:
            DEPLOY_TOKEN:
                required: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
              with:
                  version: latest
            - uses: actions/setup-node@v4
              with:
                  node-version: latest
            - run: pnpm install
            - run: pnpm run pages:docker
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: build-docker
                  path: packages/docker-proxy/pages

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/checkout@v4
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: build-docker
                  path: packages/docker-proxy/pages
            - name: Zip pages folder
              run: |
                  cd packages/docker-proxy
                  zip -r _worker.zip pages
                  mv _worker.zip pages/
            - name: List contents of pages directory
              run: ls -al packages/docker-proxy/pages
            - name: Deploy to Cloudflare Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.DEPLOY_TOKEN }}
                  publish_dir: packages/docker-proxy/pages
                  publish_branch: release-docker
                  keep_files: false
                  enable_jekyll: true
