name: Release Workflow

on:
    push:
        branches:
            - main
        paths-ignore:
            - addressesapi.txt
            - README.md
            - packages/**/*.md
            - packages/**/*.txt
            - LICENSE

jobs:
    determine_release_type:
        runs-on: ubuntu-latest
        outputs:
            release_type: ${{ steps.set_release_type.outputs.type }}
        steps:
            - name: Determine release type
              id: set_release_type
              run: |
                  commit_message="${{ github.event.head_commit.message }}"
                  if [[ "$commit_message" =~ ^registry: ]]; then
                      echo "type=registry" >> $GITHUB_OUTPUT
                  elif [[ "$commit_message" =~ ^parse: ]]; then
                      echo "type=parse" >> $GITHUB_OUTPUT
                  elif [[ "$commit_message" =~ ^feat: ]]; then
                      echo "type=feat" >> $GITHUB_OUTPUT
                  else
                      echo "type=unknown" >> $GITHUB_OUTPUT
                  fi

            - name: Print release type
              run: |
                  echo "Release type: ${{ steps.set_release_type.outputs.type }}"

    run_registry_release:
        needs: determine_release_type
        if: needs.determine_release_type.outputs.release_type == 'registry' || needs.determine_release_type.outputs.release_type == 'feat'
        uses: ./.github/workflows/release-registry.yml
        secrets:
            DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

    run_parse_release:
        needs: determine_release_type
        if: needs.determine_release_type.outputs.release_type == 'parse' || needs.determine_release_type.outputs.release_type == 'feat'
        uses: ./.github/workflows/release-parse.yml
        secrets:
            DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

    unknown_release_type:
        needs: determine_release_type
        if: needs.determine_release_type.outputs.release_type == 'unknown'
        runs-on: ubuntu-latest
        steps:
            - run: |
                  echo "Unknown release type. No action taken."
                  exit 1
