name: Release Workflow

on:
    push:
        branches:
            - main

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Determine release type
              id: release_type
              run: |
                  commit_message="${{ github.event.head_commit.message }}"
                  if [[ "$commit_message" =~ ^docker: ]]; then
                    echo "type=release-docker" >> $GITHUB_OUTPUT
                  elif [[ "$commit_message" =~ ^npmjs: ]]; then
                    echo "type=release-npm" >> $GITHUB_OUTPUT
                  else
                    echo "type=unknown" >> $GITHUB_OUTPUT
                  fi

            - name: Run Docker release workflow
              if: steps.release_type.outputs.type == 'release-docker'
              uses: ./.github/workflows/release-docker.yml

            - name: Run NPM release workflow
              if: steps.release_type.outputs.type == 'release-npm'
              uses: ./.github/workflows/release-npm.yml

            - name: Unknown release type
              if: steps.release_type.outputs.type == 'unknown'
              run: |
                  echo "Unknown release type. No action taken."
                  exit 1


