name: Release Workflow

on:
    push:
        branches:
            - main

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Determine release type
              run: |
                  commit_message="${{ github.event.head_commit.message }}"
                  if [[ "$commit_message" =~ ^docker: ]]; then
                    echo "Release type: docker"
                    RELEASE_TYPE="release-docker"
                  elif [[ "$commit_message" =~ ^npm: ]]; then
                    echo "Release type: npm"
                    RELEASE_TYPE="release-npm"
                  else
                    echo "Release type: unknown"
                    exit 1
                  fi
            - name: Run release workflow
              if: ${{ RELEASE_TYPE != 'unknown' }}
              uses: ./.github/workflows/${{ RELEASE_TYPE }}.yml
