name: build and publish

on:
    release:
        types: [created]
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
              with:
                  version: latest
            - uses: actions/setup-node@v4
              with:
                  node-version: '18'
            - run: pnpm install
            - run: pnpm run pages:docker
            - name: Upload artifact
              uses: actions/upload-artifact@v3
              with:
                  name: build
                  path: packages/docker-proxy/pages

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/checkout@v4
            - name: Download artifact
              uses: actions/download-artifact@v3
              with:
                  name: build
                  path: packages/docker-proxy/pages
            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.DEPLOY_TOKEN }}
                  publish_dir: packages/docker-proxy/pages
                  publish_branch: release-docker
                  keep_history: true # Optional, to keep the commit history
