name: Release Workflow

on:
    push:
        branches:
            - main

jobs:
    determine_release_type:
        runs-on: ubuntu-latest
        outputs:
            release_type: ${{ steps.set_release_type.outputs.type }}
        steps:
            - name: Determine release type
              id: set_release_type
              run: |
                  commit_message="${{ github.event.head_commit.message }}"
                  if [[ "$commit_message" =~ ^docker: ]]; then
                    echo "type=docker" >> $GITHUB_OUTPUT
                  elif [[ "$commit_message" =~ ^npmjs: ]]; then
                    echo "type=npm" >> $GITHUB_OUTPUT
                  else
                    echo "type=unknown" >> $GITHUB_OUTPUT
                  fi

    run_docker_release:
        needs: determine_release_type
        if: needs.determine_release_type.outputs.release_type == 'docker'
        uses: ./.github/release/release-docker.yml

    run_npm_release:
        needs: determine_release_type
        if: needs.determine_release_type.outputs.release_type == 'npm'
        uses: ./.github/release/release-npm.yml

    unknown_release_type:
        needs: determine_release_type
        if: needs.determine_release_type.outputs.release_type == 'unknown'
        runs-on: ubuntu-latest
        steps:
            - run: |
                  echo "Unknown release type. No action taken."
                  exit 1
