name: subs release

on:
    push:
        paths-ignore:
            - addressesapi.txt
            - README.md
            - packages/**/*.md
            - packages/**/*.txt
            - LICENSE

    workflow_call:
        secrets:
            DEPLOY_TOKEN:
                required: true

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
              with:
                  version: latest
            - uses: actions/setup-node@v4
              with:
                  node-version: latest
            - run: pnpm install --no-frozen-lockfile
            - run: pnpm run pages:collect-subs
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: build-subs
                  path: packages/collect-subs/pages

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/checkout@v4
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: build-subs
                  path: packages/collect-subs/pages
            - name: Zip pages folder
              run: |
                  cd packages/collect-subs
                  worker_file=$(find pages -name '*worker*.js' -type f)
                  if [ -z "$worker_file" ]; then
                      echo "Error: No worker file found"
                      exit 1
                  fi
                  echo "Found worker file: $worker_file"
                  zip -j _worker.zip "$worker_file"
                  mv _worker.zip pages/
            - name: List contents of pages directory
              run: ls -al packages/collect-subs/pages
            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.DEPLOY_TOKEN }}
                  publish_dir: packages/collect-subs/pages
                  publish_branch: release-subs
                  keep_files: false
                  enable_jekyll: true
