name: Release Workflow

on:
    push:
        branches:
            - main
        paths-ignore:
            - README.md
            - packages/**/*.md
            - LICENSE

jobs:
    determine_release_type:
        runs-on: ubuntu-latest
        outputs:
            release_type: ${{ steps.set_release_type.outputs.type }}
        steps:
            - name: Determine release type
              id: set_release_type
              run: |
                  commit_message="${{ github.event.head_commit.message }}"
                  if [[ "$commit_message" =~ ^docker: ]]; then
                      echo "type=docker" >> $GITHUB_OUTPUT
                  elif [[ "$commit_message" =~ ^npm: ]]; then
                      echo "type=npm" >> $GITHUB_OUTPUT
                  elif [[ "$commit_message" =~ ^cargo: ]]; then
                      echo "type=cargo" >> $GITHUB_OUTPUT
                  elif [[ "$commit_message" =~ ^feat: ]]; then
                      echo "type=feat" >> $GITHUB_OUTPUT
                  else
                      echo "type=unknown" >> $GITHUB_OUTPUT
                  fi

            - name: Print release type
              run: |
                  echo "Release type: ${{ steps.set_release_type.outputs.type }}"

            - name: Set current time
              id: set_time
              run: echo "TIME=$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

            - name: Print release type
              run: |
                  echo "Release type: ${{ steps.set_release_type.outputs.type }}"
                  echo "Current time: $TIME"

    run_docker_release:
        needs: determine_release_type
        if: needs.determine_release_type.outputs.release_type == 'docker'
        uses: ./.github/workflows/release-docker.yml
        secrets:
            DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        env:
            TIME: ${{ env.TIME }}

    run_npm_release:
        needs: determine_release_type
        if: needs.determine_release_type.outputs.release_type == 'npm'
        uses: ./.github/workflows/release-npm.yml
        secrets:
            DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        env:
            TIME: ${{ env.TIME }}

    run_cargo_release:
        needs: determine_release_type
        if: needs.determine_release_type.outputs.release_type == 'cargo'
        uses: ./.github/workflows/release-cargo.yml
        secrets:
            DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        env:
            TIME: ${{ env.TIME }}

    unknown_release_type:
        needs: determine_release_type
        if: needs.determine_release_type.outputs.release_type == 'unknown'
        runs-on: ubuntu-latest
        steps:
            - run: |
                  echo "Unknown release type. No action taken."
                  exit 1
