name: docker release

on:
    workflow_call:
        secrets:
            DEPLOY_TOKEN:
                required: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
              with:
                  version: latest
            - uses: actions/setup-node@v4
              with:
                  node-version: latest
            - run: pnpm install
            - run: pnpm run pages:docker
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: build
                  path: packages/docker-proxy/pages

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/checkout@v4
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: build
                  path: packages/docker-proxy/pages
            - name: Deploy to Cloudflare Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.DEPLOY_TOKEN }}
                  publish_dir: packages/docker-proxy/pages
                  publish_branch: release-docker
                  keep_files: false
                  enable_jekyll: true

    zip:
        runs-on: ubuntu-latest
        needs: deploy
        steps:
            - name: Zip Dist
              run: zip -r docker-proxy.zip . -i packages/docker-proxy/pages

            - name: create release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
              with:
                  tag_name: "docker-release-${{ github.sha }}"
                  release_name: "Docker Release ${{ github.sha }}"
                  draft: false
                  prerelease: false

            - name: upload release asset
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: docker-proxy.zip
                  asset_name: docker-proxy.zip
                  asset_content_type: application/zip
