name: cargo release

on:
    workflow_call:
        secrets:
            DEPLOY_TOKEN:
                required: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
              with:
                  version: latest
            - uses: actions/setup-node@v4
              with:
                  node-version: latest
            - run: pnpm install
            - run: pnpm run pages:cargo
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: build-cargo
                  path: packages/cargo-proxy/pages

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/checkout@v4
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: build
                  path: packages/cargo-proxy/pages
            - name: Deploy to Cloudflare Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.DEPLOY_TOKEN }}
                  publish_dir: packages/cargo-proxy/pages
                  publish_branch: release-cargo
                  keep_files: false
                  enable_jekyll: true

    release:
        runs-on: ubuntu-latest
        needs: deploy
        steps:
            - uses: actions/checkout@v4
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: build
                  path: packages/cargo-proxy/pages

            - name: Check files before zipping
              run: ls -al packages/cargo-proxy/pages

            - name: Zip Dist
              run: zip -r cargo-proxy.zip packages/cargo-proxy/pages

            - name: create release
              id: create_release
              uses: softprops/action-gh-release@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
              with:
                  tag_name: 'docker-release-${{ github.sha }}'
                  name: 'cargo-proxy'
                  draft: false
                  prerelease: false
                  files: cargo-proxy.zip
