# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: build and publish

on:
    release:
        types: [created]
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
              with:
                  version: latest
            - uses: actions/setup-node@v4
              with:
                  node-version: latest
            - run: pnpm install
            - run: pnpm run build:pages:docker
    deploy:
        uses: peaceiris/actions-gh-pages@v3
        with:
            deploy_key: ${{ secrets.DEPLOY_TOKEN }}
            external_repository: https://github.com/jwyGithub/cloudflare-workers.git
            publish_dir: ./packages/docker-proxy/pages
            keep_files: false
            publish_branch: release-docker
